version: '3'
services:
  nginx:
    image: 'nginx:latest'
    depends_on:
      - php7
      - php5
    ports:
      - 80:80
    volumes:
      - '../src:/code'
      - './config/nginx/nginx_with_php.conf:/etc/nginx/conf.d/default.conf'
    container_name: example_nginx

  php7:
    image: php:7.2-fpm
    volumes:
      - '../src:/code'
    container_name: php

  php5:
    image: php:5.6-fpm
    volumes:
      - '../src:/code'
    container_name: php5

# Do not forget to 'docker network create docker-demo' before launch,

networks:
  default:
    external:
      name: docker-demo
